# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hangman_pb2 as hangman__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hangman_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HangmanServiceStub(object):
    """The Hangman service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/hangman.HangmanService/JoinGame',
                request_serializer=hangman__pb2.PlayerRequest.SerializeToString,
                response_deserializer=hangman__pb2.GameState.FromString,
                _registered_method=True)
        self.GuessLetter = channel.unary_unary(
                '/hangman.HangmanService/GuessLetter',
                request_serializer=hangman__pb2.GuessRequest.SerializeToString,
                response_deserializer=hangman__pb2.GameState.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_unary(
                '/hangman.HangmanService/GetGameState',
                request_serializer=hangman__pb2.PlayerRequest.SerializeToString,
                response_deserializer=hangman__pb2.GameState.FromString,
                _registered_method=True)
        self.LeaveGame = channel.unary_unary(
                '/hangman.HangmanService/LeaveGame',
                request_serializer=hangman__pb2.PlayerRequest.SerializeToString,
                response_deserializer=hangman__pb2.LeaveResponse.FromString,
                _registered_method=True)


class HangmanServiceServicer(object):
    """The Hangman service definition
    """

    def JoinGame(self, request, context):
        """A player joins the game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GuessLetter(self, request, context):
        """A player makes a guess
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """A player requests the current game state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """A player leaves the game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HangmanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=hangman__pb2.PlayerRequest.FromString,
                    response_serializer=hangman__pb2.GameState.SerializeToString,
            ),
            'GuessLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.GuessLetter,
                    request_deserializer=hangman__pb2.GuessRequest.FromString,
                    response_serializer=hangman__pb2.GameState.SerializeToString,
            ),
            'GetGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=hangman__pb2.PlayerRequest.FromString,
                    response_serializer=hangman__pb2.GameState.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=hangman__pb2.PlayerRequest.FromString,
                    response_serializer=hangman__pb2.LeaveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hangman.HangmanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hangman.HangmanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HangmanService(object):
    """The Hangman service definition
    """

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hangman.HangmanService/JoinGame',
            hangman__pb2.PlayerRequest.SerializeToString,
            hangman__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GuessLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hangman.HangmanService/GuessLetter',
            hangman__pb2.GuessRequest.SerializeToString,
            hangman__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hangman.HangmanService/GetGameState',
            hangman__pb2.PlayerRequest.SerializeToString,
            hangman__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hangman.HangmanService/LeaveGame',
            hangman__pb2.PlayerRequest.SerializeToString,
            hangman__pb2.LeaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
